# Generated by Django 3.2.15 on 2024-06-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0003_remove_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
