# Generated by Django 3.2.15 on 2024-06-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0005_auto_20240625_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(default='folder', max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
