# Generated by Django 3.2.15 on 2024-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0009_remove_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(default='folder', max_length=50),
        ),
    ]
